### ISSUE TITLE
Would you release the lecture videos 

### ISSUE THREAD

**Issue by hao-zheng-uoa** [UT-Austin-RPL/cs391r-website#1]
I found that I can't get the lecture videos from the course website. Does it mean that students who are not from UTA can't get the videos? I think this course is great. Really wish I can learn it.

**Comment by yukezhu** [comment]
Due to privacy concerns, we won't be able to release our videos to students outside UTA. You will be able to find our lecture slides and other reading materials from the course website for self-study.
